//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEV1301
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabUsuario
    {
        public long codigo { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public Nullable<System.DateTime> dataCadastrado { get; set; }
        public Nullable<System.DateTime> dataUltimoAcesso { get; set; }
    }
}
